services:
  backend:
    image: uskharlamova/abntester-backend:main
    environment:
      - CORS_ORIGINS=${CORS_ORIGINS}
    ports:
      - "8080:8080"
  frontend:
    image: uskharlamova/abntester-frontend:main
    ports:
      - "443:4200"
      - "80:4200"
