name: abntester-ci-cd
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
      - run: npm install --legacy-peer-deps
        working-directory: ./abntester-frontend
      - run: npm run build
        working-directory: ./abntester-frontend
      - uses: actions/upload-artifact@master
        with:
          name: dist
          path: abntester-frontend/dist/
  docker-frontend-push:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: dist
          path: abntester-frontend/dist/
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: uskharlamova/abntester-frontend
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./abntester-frontend
          file: abntester-frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        working-directory: ./abntester-backend
        run: mvn package
      - uses: actions/upload-artifact@master
        with:
          name: target
          path: abntester-backend/target/
  docker-backend-push:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: target
          path: abntester-backend/target/
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: uskharlamova/abntester-backend
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./abntester-backend
          file: abntester-backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: [ docker-backend-push, docker-frontend-push ]
    runs-on: ubuntu-latest
    env:
      CORS_ORIGINS: ${{ secrets.CORS_ORIGINS }}
    steps:
      - uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          envs: CORS_ORIGINS
          script: |
            cd ABnTester
            git pull
            docker pull uskharlamova/abntester-backend:main
            docker pull uskharlamova/abntester-frontend:main
            docker-compose stop
            docker-compose up -d
